[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend"
readme = "README.md"
requires-python = ">=3.12.7"

dependencies = [
    "fastapi>=0.104,<0.130",
    "uvicorn[standard]>=0.24.0",
    "sqlalchemy>=2.0.23",
    "sqlmodel>=0.0.14",
    "psycopg2-binary>=2.9.7",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "pyjwt>=2.8.0",
    "python-multipart>=0.0.6",
    "python-dotenv>=1.0.0",
    "cryptography>=41.0.7"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["backend*", "auth*", "models*", "routes*", "schemas*"]
